-- List all unique cities where customers are located.
Select Distinct(customer_city) as Unique_cities from orderdetails.customers;

-- Count the number of orders placed in 2017.
select count(order_id) as orders_in_2017 from orders
where year(order_purchase_timestamp) = 2017;

-- Find the total sales per category.
select round(sum(o.price),2) as total_sales , p.product_category from products p
join order_items o on p.product_id = o.product_id
group by p.product_category;

 -- Calculate the percentage of orders that were paid in installments. 
select count(distinct order_id) as total_orders , round(sum(payment_installments>1)*100/count(distinct order_id),2) as paid_in_installments from payments;

-- Count the number of customers from each state
select count(customer_id) , customer_state from customers
group by customer_state;

-- Calculate the number of orders per month in 2018.
select month(order_purchase_timestamp) as order_month ,count(order_id) as total_order from orders
where year(order_purchase_timestamp) = 2018
group by month(order_purchase_timestamp );

-- Find the average number of products per order, grouped by customer city. 
SELECT customer_city, AVG(products_count) AS avg_products_per_order
FROM (
    SELECT c.customer_city, o.order_id, COUNT(oi.order_item_id) AS products_count FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY c.customer_city, o.order_id
)
GROUP BY customer_city;

-- Calculate the percentage of total revenue contributed by each product category. 
select p.product_category, round(sum(o.price)*100/( select sum(price) from order_items),2) as total_revenue
from products p join order_items o
on p.product_id = o.product_id
group by product_category;

-- Identify the correlation between product price and the number of times a product has been purchased. 
SELECT 
    (AVG(unit_price * purchase_count) - AVG(unit_price) * AVG(purchase_count)) / 
    (STDDEV(unit_price) * STDDEV(purchase_count)) AS correlation_coefficient
FROM (
    SELECT product_id, AVG(price) AS unit_price, COUNT(order_id) AS purchase_count FROM order_items
    GROUP BY product_id ) AS product_stats; -- showing  No relation

-- calculate the total revenue generated by each seller, and rank them by revenue.
select round(sum(o.price),2) as total_revenue  , s.seller_id as seller  from order_items o join sellers s 
on o.seller_id = s.seller_id
group by seller
order by total_revenue desc;

-- Calculate the moving average of order values for each customer over their order history.
select distinct o.customer_id, oi.price, o.order_purchase_timestamp , round(avg(oi.price) over(partition by o.customer_id order by o.order_purchase_timestamp),2) as moving_average
from orders o join order_items oi on o.order_id = oi.order_id;

--  Calculate the cumulative sales per month for each year.
select  month(o.order_purchase_timestamp) as month , year(o.order_purchase_timestamp) as year, sum(oi.price) as monthly_sales, 
sum(sum(oi.price)) over(partition By Year(o.order_purchase_timestamp)
order by month(o.order_purchase_timestamp)) as cumulative_sales
from orders o join order_items oi on o.order_id = oi.order_id
group by year, month;

-- Calculate the year-over-year growth rate of total sales.
WITH yearlysales AS (
    SELECT YEAR(o.order_purchase_timestamp) AS year,
        SUM(oi.price) AS revenue
    FROM orders o
    JOIN order_items oi 
        ON o.order_id = oi.order_id
    GROUP BY YEAR(o.order_purchase_timestamp)
    )
SELECT 
    year, revenue, LAG(revenue) OVER(ORDER BY year) AS last_year_revenue,
    ROUND(
        ((revenue - LAG(revenue) OVER(ORDER BY year))
        / LAG(revenue) OVER(ORDER BY year)) * 100,
    2) AS yoy_growth_rate FROM yearlysales;


-- Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase. 
SELECT ROUND(
    COUNT(DISTINCT o.customer_id) * 100.0 /
    (SELECT COUNT(DISTINCT customer_id) FROM orders),2) AS retention_rate FROM orders o
JOIN (
    SELECT customer_id,
           MIN(order_purchase_timestamp) AS first_purchase
    FROM orders
    GROUP BY customer_id
) first_orders
ON o.customer_id = first_orders.customer_id
WHERE o.order_purchase_timestamp > first_orders.first_purchase
AND o.order_purchase_timestamp <= 
DATE_ADD(first_orders.first_purchase, INTERVAL 6 MONTH);
 
 
--  Identify the top 3 customers who spent the most money in each year.
select o.customer_id, sum(oi.price) , year(o.order_purchase_timestamp) from orders o join order_items oi
on o.order_id = oi.order_id
group by year(o.order_purchase_timestamp)
order by sum(oi.price) desc;
 













