--  List all unique cities where customers are located.
Select customer_city as Unique_cities, count(customer_city) as City_count
from orderdetails.customers
group by customer_city
order by count(customer_city) desc;


-- Count the number of orders placed in 2017.
select count(Distinct order_id) as orders_in_2017 from orders
where year(order_purchase_timestamp) = 2017;


-- Find the total sales per category.
select round(sum(o.price),2) as total_sales , p.product_category
from products p
join order_items o on p.product_id = o.product_id
group by p.product_category
order by total_sales desc;


 -- Calculate the percentage of orders that were paid in installments. 
select count(distinct order_id) as total_orders ,
round(sum(payment_installments>1)*100/count(distinct order_id),2)
as paid_in_installments
from payments;


-- Count the number of customers from each state
select count(customer_id) as total_customer,
customer_state from customers
group by customer_state
order by total_customer desc;


-- Calculate the number of orders per month in 2018.
select month(order_purchase_timestamp) as order_month_2018 ,count(distinct order_id) as total_order
from orders
where year(order_purchase_timestamp) = 2018
group by month(order_purchase_timestamp );


-- Find the average number of products per order, grouped by customer city. 
SELECT customer_city, AVG(products_count) AS avg_products_per_order
FROM (
    SELECT c.customer_city, o.order_id, COUNT(Distinct oi.order_item_id) AS products_count
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY c.customer_city, o.order_id
) as order_counts
GROUP BY customer_city
order by avg_products_per_order desc;


-- Calculate the percentage of total revenue contributed by each product category. 
select p.product_category,
round(sum(o.price)*100/( select sum(price) from order_items),2) as total_revenue
from products p join order_items o
on p.product_id = o.product_id
group by product_category
order by total_revenue desc;


-- Identify the correlation between product price and the number of times a product has been purchased. 
SELECT 
    (AVG(unit_price * purchase_count) - AVG(unit_price) * AVG(purchase_count)) / 
    (STDDEV(unit_price) * STDDEV(purchase_count)) AS correlation_coefficient
FROM (
    SELECT product_id, AVG(price) AS unit_price, COUNT(order_id) AS purchase_count
    FROM order_items
    GROUP BY product_id ) AS product_stats; -- showing  No relation
    

-- calculate the total revenue generated by each seller, and rank them by revenue.
select round(sum(o.price),2) as total_revenue  , s.seller_id as seller  
from order_items o join sellers s 
on o.seller_id = s.seller_id
group by seller
order by total_revenue desc;


-- Calculate the moving average of order values for each customer over their order history.
SELECT Distinct
    c.customer_unique_id, o.order_purchase_timestamp as order_year, ot.order_value,
    AVG(ot.order_value) OVER(
        PARTITION BY c.customer_unique_id 
        ORDER BY o.order_purchase_timestamp
    ) AS moving_avg
FROM orders o
JOIN (SELECT order_id, SUM(price) AS order_value FROM order_items
group by order_id) ot
    ON o.order_id = ot.order_id
JOIN customers c 
    ON o.customer_id = c.customer_id
ORDER BY year(o.order_purchase_timestamp) asc, ot.order_value desc;


--  Calculate the cumulative sales per month for each year.
select year(o.order_purchase_timestamp) as year, month(o.order_purchase_timestamp) as month,
sum(oi.price) as monthly_sales, 
sum(sum(oi.price)) over(partition By Year(o.order_purchase_timestamp)
order by month(o.order_purchase_timestamp)) as cumulative_sales
from orders o join order_items oi on o.order_id = oi.order_id
-- where o.order_status = "delivered"
group by year, month;



-- Calculate the year-over-year growth rate of total sales.
WITH yearlysales AS (
    SELECT YEAR(o.order_purchase_timestamp) AS year,
        SUM(oi.price) AS revenue
    FROM orders o
    JOIN order_items oi 
        ON o.order_id = oi.order_id
    GROUP BY year
    )
SELECT 
    year, revenue, LAG(revenue) OVER(ORDER BY year) AS lastyear_revenue,
    ROUND(((revenue - LAG(revenue) OVER(ORDER BY year)) / LAG(revenue) OVER(ORDER BY year)) * 100,2) 
    AS yoy_growth_rate FROM yearlysales;
    

-- Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase.  
WITH FirstPurchase AS (
    SELECT c.customer_unique_id, 
	MIN(o.order_purchase_timestamp) AS first_order_date
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id ),
RetainedCustomers AS (
    SELECT DISTINCT f.customer_unique_id
    FROM FirstPurchase f
    JOIN customers c ON f.customer_unique_id = c.customer_unique_id
    JOIN orders o ON c.customer_id = o.customer_id
    WHERE o.order_purchase_timestamp > f.first_order_date 
      AND o.order_purchase_timestamp <= DATE_ADD(f.first_order_date, INTERVAL 6 MONTH))
SELECT 
    (SELECT COUNT(*) FROM FirstPurchase) AS total_customers,
    (SELECT COUNT(*) FROM RetainedCustomers) AS retained_customers,
    ROUND(
        (SELECT COUNT(*) FROM RetainedCustomers) * 100.0 / (SELECT COUNT(*) FROM FirstPurchase),2)
        AS retention_rate;

 
--  Identify the top 3 customers who spent the most money in each year.
Select order_year, customer_unique_id, total_spent
from (
SELECT YEAR(o.order_purchase_timestamp) AS order_year, c.customer_unique_id,
SUM(oi.price) AS total_spent,
DENSE_RANK() OVER (
PARTITION BY YEAR(o.order_purchase_timestamp) 
ORDER BY SUM(oi.price) DESC
) AS customer_rank
FROM orders o
JOIN customers c on o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY order_year, c.customer_unique_id
) AS ranked_customers
WHERE customer_rank <= 3
ORDER BY order_year DESC, total_spent desc;
 
 WITH YearlySpending AS (
    SELECT 
        YEAR(o.order_purchase_timestamp) AS order_year, 
        c.customer_unique_id, 
        SUM(oi.price)AS total_spent,
        DENSE_RANK() OVER (
            PARTITION BY YEAR(o.order_purchase_timestamp) 
            ORDER BY SUM(oi.price)desc
        ) AS customer_rank
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered' 
    GROUP BY YEAR(o.order_purchase_timestamp), c.customer_unique_id
)
SELECT 
    order_year, customer_unique_id, total_spent
FROM YearlySpending
WHERE customer_rank <= 3
ORDER BY order_year DESC, total_spent desc;



